# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('am', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('linkedin_url', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('knowledge', models.TextField()),
                ('skills', models.TextField()),
                ('preferred_teams', models.TextField()),
                ('image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postit.Team'),
        ),
    ]
