# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0004_auto_20201013_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_url',
            field=models.FileField(upload_to='media'),
        ),
    ]
