# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-13 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0005_auto_20201013_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('am',)},
        ),
    ]
