# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0006_auto_20201013_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_teams',
            field=models.TextField(blank=True),
        ),
    ]
