# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-14 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0009_auto_20201013_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name',)},
        ),
    ]
